apiVersion: v1
kind: Namespace
metadata:
  name: kube-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cilium
  namespace: kube-system
spec:
  repo: https://helm.cilium.io/
  chart: cilium
  targetNamespace: kube-system
  version: "1.16.2"
  valuesContent: |-
    kubeProxyReplacement: "true"
    k8sServiceHost: <API_IP>
    k8sServicePort: "6443"
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
        ingress:
          enabled: true
          hosts:
            - hubble.minilab.sh
      metrics:
        enabled:
          - dns
          - drop
          - tcp
          - flow
          - icmp
          - http
