apiVersion: v1
kind: Namespace
metadata:
  name: keda
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: keda
  namespace: kube-system
spec:
  repo: https://kedacore.github.io/charts
  chart: keda
  targetNamespace: keda