apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: nginx-autoscale-keda
  namespace: nginx-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-autoscale
  pollingInterval: 10
  cooldownPeriod: 30
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
        metricName: nginx_http_requests_total
        threshold: "100"
        query: sum(irate(nginx_http_requests_total[5m]))