---
apiVersion: v1
kind: Namespace
metadata:
  name: envoy-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-proxy
  namespace: envoy-proxy
  labels:
    app.kubernetes.io/instance: envoy-proxy
    app.kubernetes.io/name: envoy-proxy
    role: proxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: envoy-proxy
      app.kubernetes.io/name: envoy-proxy
      role: proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: envoy-proxy
        app.kubernetes.io/name: envoy-proxy
        role: proxy
    spec:
      containers:
      - name: envoy
        image: envoyproxy/envoy:v1.32.0
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: envoy-config-volume
          readOnly: true
          mountPath: /etc/envoy/
        args:
          - "/usr/local/bin/envoy"
          - "-c"
          - "/etc/envoy/envoy.yaml"
      volumes:
      - name: envoy-config-volume
        configMap:
          name: envoy-proxy-config
          items:
            - key: envoy.yaml
              path: envoy.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-proxy
  namespace: envoy-proxy
spec:
  selector:
    app.kubernetes.io/instance: envoy-proxy
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-proxy-config
  namespace: envoy-proxy
data:
  envoy.yaml: |
    admin:
      address:
        socket_address:
          protocol: TCP
          address: 127.0.0.1
          port_value: 9901
    static_resources:
      listeners:
      - name: listener_0
        address:
          socket_address:
            protocol: TCP
            address: 0.0.0.0
            port_value: 80
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: egress_http
              http_protocol_options:
                accept_http_10: true
              http2_protocol_options:
                allow_connect: true
              upgrade_configs:
                upgrade_type: CONNECT
              access_log:
              - name: envoy.access_loggers.stdout
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
              route_config:
                name: local_route
                virtual_hosts:
                - name: local_service
                  domains: ["*"]
                  routes:
                  - match:
                      connect_matcher: {}
                    route:
                      cluster: dynamic_forward_proxy_cluster
                      upgrade_configs:
                        - upgrade_type: CONNECT
                          connect_config: {}
                  - match:
                      prefix: "/"
                    route:
                      cluster: dynamic_forward_proxy_cluster          
              http_filters:
              - name: envoy.filters.http.dynamic_forward_proxy
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
                  dns_cache_config:
                    name: dynamic_forward_proxy_cache_config
                    dns_lookup_family: V4_ONLY
                    typed_dns_resolver_config:
                      name: envoy.network.dns_resolver.cares
                      typed_config:
                        "@type": type.googleapis.com/envoy.extensions.network.dns_resolver.cares.v3.CaresDnsResolverConfig
                        resolvers:
                        - socket_address:
                            address: "8.8.8.8"
                            port_value: 53
                        dns_resolver_options:
                          use_tcp_for_dns_lookups: true
                          no_default_search_domain: true
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      clusters:
      - name: dynamic_forward_proxy_cluster
        lb_policy: CLUSTER_PROVIDED
        cluster_type:
          name: envoy.clusters.dynamic_forward_proxy
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
            dns_cache_config:
              name: dynamic_forward_proxy_cache_config
              dns_lookup_family: V4_ONLY
              typed_dns_resolver_config:
                name: envoy.network.dns_resolver.cares
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.network.dns_resolver.cares.v3.CaresDnsResolverConfig
                  resolvers:
                  - socket_address:
                      address: "8.8.8.8"
                      port_value: 53
                  dns_resolver_options:
                    use_tcp_for_dns_lookups: true
                    no_default_search_domain: true